---
# List of plays
-
  # Hosts: where our play will run and options it will run with
  hosts: localhost
  connection: local
  gather_facts: yes
  tags: always

  # Vars: variables that will apply to the play, on all targets 

  # Tasks: the list of tasks that will be executed within 
  #        the play, this section can also be used for 
  #        pre and post tasks
  tasks:
    # from https://superuser.com/questions/1395954/ansible-playbook-to-determine-os-release
  - name: System details
    debug: msg="{{ item }}"
    with_items: 
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    - "{{ ansible_distribution_major_version }}"
    # Detect if we are running on a WSL2 environment
  - name: Set wsl2_environment fact default to false
    set_fact:
      wsl2_environment: false
  - name: Set wsl2_environment fact True
    set_fact:
      wsl2_environment: true
    when: ansible_kernel is search("microsoft-standard-WSL2")  
  # fix for .gnupg/ permissions when building custom images
  - name: Add fix for .gnupg/ permissions
    lineinfile:
      path: "/etc/bash.bashrc"
      line: "chmod 700 ~/.gnupg/"    
  - name: Add custom prompt to /etc/skel/.profile
    lineinfile:
      path: "/etc/skel/.profile"
      line: 'export PS1="\[\033[00;32m\][\w]\$\[\033[00m\] "'

  # Handlers: the list of handlers that are executed as a notify 
  #           key from a task

  # Roles: list of roles to be imported into the play
  roles:
  - role: irixjp.role_example_hello

# Add additional plays here (remember the list entry -)
# Be sure to use the same hosts and connection entries above
# addtional plays

-
  # Install build-essential
  hosts: localhost
  connection: local
  tags:
  - install_doxygen
  - install_cross_compile_toolchain

  tasks:
  - name: Install build-essential
    apt:
      name: build-essential
      update_cache: yes

-
  # install OpenJDK 11
  hosts: localhost
  connection: local
  tasks:
  - name: Download OpenJDK 11 tarball
    shell: wget https://download.java.net/openjdk/jdk11/ri/openjdk-11+28_linux-x64_bin.tar.gz -O /home/kasm-default-profile/openjdk-11+28_linux-x64_bin.tar.gz
  - name: Extract OpenJDK 11 binaries
    unarchive:
      src: /home/kasm-default-profile/openjdk-11+28_linux-x64_bin.tar.gz
      dest: /opt
      remote_src: yes
      creates: /opt/jdk-11/release
  - name: Delete OpenJDK 11 tarball
    shell: rm /home/kasm-default-profile/openjdk-11+28_linux-x64_bin.tar.gz
  - name: Update alternatives so the command, java, points to installed jdk
    shell: update-alternatives --install /usr/bin/java java /opt/jdk-11/bin/java 100
  - name: Update alternatives so the command, javac, points to installed jdk
    shell: update-alternatives --install /usr/bin/javac javac /opt/jdk-11/bin/javac 100

-
  # install chrome
  hosts: localhost
  connection: local
  gather_facts: yes

  roles:
    - role: webarchitect609.google_chrome

-
  # install keychain, git, and @capsulecorplab .vimrc and .gitconfig
  hosts: localhost
  connection: local
  gather_facts: yes
  tags: install_utilities

  vars:
    git_version: "2.41.0"
    git_version_to_install: "1:{{ git_version }}-0ppa1~ubuntu22.04.1"
    keychain_version: "2.8.5"
    keychain_version_to_install: "{{ keychain_version }}-2"
    keychain_version_expected: "{{ keychain_version }}.."

  tasks:
  - name: Add git PPA
    shell: add-apt-repository ppa:git-core/ppa
  - name: Install git
    apt:
      name: "git={{ git_version_to_install }}"
  - name: Install Git Bash Completion
    apt:
      name: bash-completion
      update_cache: yes
  - name: Install Keychain
    apt:
      name: "keychain={{ keychain_version_to_install }}"
      update_cache: yes
  - name: install ping
    apt:
      name: iputils-ping
      update_cache: yes
  - name: Get git version
    shell: git version | sed 's/[[:alpha:]|(|[:space:]]//g'
    register: installed_git_version
  - name: Get keychain version
    shell:
      cmd: keychain -V 2> >(grep -i keychain) 2> >(sed 's/[[:alpha:]|(|[:space:]]//g') | fgrep '*' | sed 's/[*~://]//g'
      executable: /bin/bash
    register: installed_keychain_version
  - name: Display git and keychain versions
    debug:
      msg: "git = {{ installed_git_version.stdout }} | keychain = {{ installed_keychain_version.stdout }}"
  - name: Test git version
    fail:
      msg: "Git Version Error: Expected {{ git_version }} | Found {{ installed_git_version.stdout }}"
    when: installed_git_version.stdout != git_version
  - name: Test keychain version
    fail:
      msg: "Keychain Version Error: Expected {{ keychain_version_expected }} | Found {{ installed_keychain_version.stdout }}"
    when: installed_keychain_version.stdout != keychain_version_expected
  - name: auto-launch keychain in shell, if ssh keys exists
    shell: echo 'if [ -r ~/.ssh/id_ed25519 ]; then\n    eval `keychain --eval id_ed25519`\nfi' >> /home/kasm-default-profile/.bashrc
  - name: Install @capsulecorplab .vimrc
    get_url:
      url: https://gist.githubusercontent.com/capsulecorplab/495058e7a57ed8adaed3c40c80d09739/raw/4a6e6f6ff92b96919be111c9cbb5a4a21ab472d2/.vimrc
      dest: /home/kasm-default-profile/
  - name: Install @capsulecorplab .gitconfig
    get_url:
      url: https://gist.githubusercontent.com/capsulecorplab/401ba2fe0857a328f2a626adbf078cc6/raw/b89a6234f0d620ff60bcfe37f95de197b8772377/.gitconfig
      dest: /home/kasm-default-profile/

-
  # install Cross-compile toolchain for embedded Linux target
  hosts: localhost
  connection: local
  tags:
  - install_cross_compile_toolchain
  - install_doxygen

  tasks:
  - name: Install gcc-arm-linux-gnueabihf with Apt
    apt:
      name: gcc-arm-linux-gnueabihf
      update_cache: yes
  - name: Install g++-arm-linux-gnueabihf with Apt
    apt:
      name: g++-arm-linux-gnueabihf
      update_cache: yes
  - name: Install gdb-multiarch with Apt
    apt:
      name: gdb-multiarch
      update_cache: yes
  - name: Install libssl-dev
    apt:
      name: libssl-dev
      update_cache: yes
  - name: Download cmake tarball
    shell: wget http://www.cmake.org/files/v3.23/cmake-3.23.1.tar.gz -O /home/kasm-default-profile/cmake-3.23.1.tar.gz
  - name: Extract cmake source files
    unarchive:
      src: /home/kasm-default-profile/cmake-3.23.1.tar.gz
      dest: /home/kasm-default-profile/
      remote_src: yes
      creates: /home/kasm-default-profile/cmake-3.23.1/README
  - name: Delete cmake tarball
    shell: rm /home/kasm-default-profile/cmake-3.23.1.tar.gz
  - name: Build cmake
    shell:
      cmd: ./configure && make > /tmp/cmake_build_output.txt 2>&1 && make install
      chdir: /home/kasm-default-profile/cmake-3.23.1/
      executable: /bin/bash
  - name: Delete cmake source files
    shell: rm -rf /home/kasm-default-profile/cmake-3.23.1/

-
  # install Python packages with pip
  hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
  - name: Update OS to point python to python3
    apt:
      name: python-is-python3
      update_cache: yes
  - name: Install pip for python3 with Apt
    apt:
      name: python3-pip
      update_cache: yes
  - name: Install python packages with pip
    pip:
      name:
        - jupyterlab
        - notebook
        - voila
        - pint
        - setuptools
  - name: Install fprime python packages & dependencies
    pip:
      requirements: https://raw.githubusercontent.com/nasa/fprime/v3.2.0/requirements.txt

-
  # install/configure fprime-system-reference and OpenCV
  hosts: localhost
  connection: local
  gather_facts: yes
  tags: install_fprime_system_reference

  vars:
    opencv_version: "4.7.0"

  tasks:
  - name: Recursively clone fprime-system-reference
    shell: git clone --recursive -b update-fprime-system-reference-to-use-fprime-v3.2.0 https://github.com/capsulecorplab/fprime-system-reference.git
  - name: Download OpenCV source tarball
    shell:
      cmd: wget https://github.com/opencv/opencv/archive/refs/tags/{{ opencv_version }}.tar.gz -O /home/kasm-default-profile/opencv-{{ opencv_version }}.tar.gz
  - name: Extract OpenCV source tarball
    unarchive:
      src: /home/kasm-default-profile/opencv-{{ opencv_version }}.tar.gz
      dest: /home/kasm-default-profile
      remote_src: yes
      creates: /home/kasm-default-profile/opencv-{{ opencv_version }}/LICENSE
  - name: Create OpenCV build directory
    shell:
      cmd: mkdir -p /home/kasm-default-profile/opencv-{{ opencv_version }}/build
  - name: Build OpenCV
    shell:
      cmd: cmake -D CMAKE_BUILD_TYPE=RELEASE -DCMAKE_TOOLCHAIN_FILE=/home/kasm-default-profile/fprime-system-reference/fprime/cmake/toolchain/raspberrypi.cmake -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=ON -DBUILD_DOCS=OFF -DWITH_V4L=ON -DWITH_LIBV4L=ON -DCMAKE_INSTALL_PREFIX=opt/ -DOpenCV_DIR=/Payload/build/ -DBUILD_SHARED_LIBS=OFF ../opencv/ && make > /tmp/opencv_build_output.txt 2>&1
      chdir: /home/kasm-default-profile/opencv-{{ opencv_version }}/build
      executable: /bin/bash

-
  # install Doctools
  hosts: localhost
  connection: local
  gather_facts: yes
  tags: install_doxygen

  vars:
    doxygen_version: "1.9.6"

  tasks:
  - name: Install doxygen dependencies # as per https://stackoverflow.com/questions/50986047/doxygen-could-not-find-flex-missing-flex-executable
    apt:
      name: flex, bison
      update_cache: yes
  - name: Download Doxygen tarball
    shell:
      cmd: wget https://github.com/doxygen/doxygen/releases/download/Release_{{ doxygen_version | replace(".","_") }}/doxygen-{{ doxygen_version }}.src.tar.gz -O /home/kasm-default-profile/doxygen-{{ doxygen_version }}.src.tar.gz
  - name: Extract Doxygen tarball
    unarchive:
      src: /home/kasm-default-profile/doxygen-{{ doxygen_version }}.src.tar.gz
      dest: /opt
      remote_src: yes
      creates: /opt/doxygen-{{ doxygen_version }}/README.md
  - name: Create Doxygen build directory
    shell:
      cmd: mkdir -p /opt/doxygen-{{ doxygen_version }}/build
  - name: Delete Doxygen tarball
    shell:
      cmd: rm /home/kasm-default-profile/doxygen-{{ doxygen_version }}.src.tar.gz
  - name: Build Doxygen
    shell:
      cmd: cmake -G "Unix Makefiles" .. && make > /tmp/doxygen_build_output.txt 2>&1 && make install
      chdir: /opt/doxygen-{{ doxygen_version }}/build
      executable: /bin/bash

- 
  # install sudo for the vs-code role below 
  hosts: localhost
  connection: local
  tasks:
  - name: Install Sudo
    apt:
      name: sudo
      update_cache: yes
  - name: Preserve DONT_PROMPT_WSL_INSTALL in sudoers
    lineinfile:
      path: "/etc/sudoers"
      line: "Defaults        env_keep += \"DONT_PROMPT_WSL_INSTALL\""
    when: wsl2_environment

-
# add dev user to give vs code somewhere to install extensions
  hosts: localhost
  connection: local
  tasks:
  - name: Add dev user
    user:
      name: dev
      uid: 1001

-
  # install the remainder of the tools
  hosts: localhost
  connection: local
  environment: 
    DONT_PROMPT_WSL_INSTALL: 1
  roles:
    - role: gantsign.visual-studio-code
      users:
        - username: "dev"
          visual_studio_code_extensions:
            - ms-python.python
          visual_studio_code_settings_overwrite: yes
          visual_studio_code_settings: {
            "extensions.ignoreRecommendations": true,
            "update.mode": "none",
            "extensions.autoUpdate": false,
            "extensions.autoCheckUpdates": false,
            "terminal.integrated.profiles.linux": {
              "bash (login)": {
                "path": "bash",
                "args": ["-l"]
                }
              },
            "terminal.integrated.defaultProfile.linux": "bash (login)" 
          }  

-
  # Copy VS Code changes to kasm-default-profile and lean up (remove) dev user now that vs code is installed
  hosts: localhost
  connection: local
  tasks:
  - name: Copy VS Code changes to kasm-default-profile
    shell: 
      cmd: cp -r /home/dev/.config/Code/ /home/kasm-default-profile/.config/Code/ && cp -r /home/dev/.vscode/ /home/kasm-default-profile/.vscode/
  - name: Remove dev user
    user:
      name: dev
      state: absent
      remove: yes 

# Three dots indicate the end of a YAML document
...
