# This is a basic workflow to help you get started with Actions

name: Build FPrime Projects

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    paths-ignore:
      - 'devResources/**'
      - 'docker-compose.yml'
      - '.gitignore'
      - 'LICENSE.md'
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'devResources/**'
      - 'docker-compose.yml'
      - '.gitignore'
      - 'LICENSE.md'
      - 'README.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout github repo
        uses: actions/checkout@v4

      - name: Show disk usage
        run: df -h

      - name: Build image with fprime projects
        uses: docker/build-push-action@v5
        with:
          file: ./fprime-projects.Dockerfile

      - name: Show disk usage
        run: df -h

      - name: Purge docker images from system to create space
        run: docker rmi -f $(docker images -aq)

